import { SwapHubTokenABI } from "./SwapHubTokenABI";
import { SwapHubDEXABI } from "./SwapHubDEXABI";

// Sepolia Testnet Chain ID
export const SEPOLIA_CHAIN_ID = 11155111;

// Network Configuration
export const NETWORKS = {
  sepolia: {
    chainId: SEPOLIA_CHAIN_ID,
    name: "Sepolia Testnet",
    rpcUrl: "https://sepolia.infura.io/v3/your-infura-key",
    blockExplorer: "https://sepolia.etherscan.io",
    currency: {
      name: "Sepolia ETH",
      symbol: "ETH",
      decimals: 18,
    },
  },
  hardhat: {
    chainId: 31337,
    name: "Hardhat Local",
    rpcUrl: "http://127.0.0.1:8545",
    blockExplorer: "",
    currency: {
      name: "Hardhat ETH",
      symbol: "ETH",
      decimals: 18,
    },
  },
};

// Contract Addresses - Update these after deployment
export interface DeployedContracts {
  dex: string;
  tokens: {
    [symbol: string]: string;
  };
}

// Default empty addresses (to be filled after deployment)
export const DEPLOYED_CONTRACTS: DeployedContracts = {
  dex: "",
  tokens: {
    SHUB: "", // SwapHub Token
    USDT: "", // Tether USD
    LINK: "", // Chainlink
    UNI: "",  // Uniswap
  },
};

// Token configurations for deployment
export const TOKEN_CONFIGS = {
  SHUB: {
    name: "SwapHub Token",
    symbol: "SHUB",
    decimals: 18,
    initialSupply: "1000000", // 1 million
    maxSupply: "10000000",    // 10 million
    faucetAmount: "100",      // 100 tokens per claim
    logo: "🔷",
    priceInUSD: 0.10,
  },
  USDT: {
    name: "Tether USD",
    symbol: "USDT",
    decimals: 6,
    initialSupply: "10000000", // 10 million
    maxSupply: "0",            // Unlimited
    faucetAmount: "1000",      // 1000 USDT per claim
    logo: "💵",
    priceInUSD: 1.00,
  },
  LINK: {
    name: "Chainlink Token",
    symbol: "LINK",
    decimals: 18,
    initialSupply: "100000",   // 100k
    maxSupply: "1000000",      // 1 million
    faucetAmount: "10",        // 10 LINK per claim
    logo: "⬡",
    priceInUSD: 15.00,
  },
  UNI: {
    name: "Uniswap Token",
    symbol: "UNI",
    decimals: 18,
    initialSupply: "100000",   // 100k
    maxSupply: "1000000",      // 1 million
    faucetAmount: "20",        // 20 UNI per claim
    logo: "🦄",
    priceInUSD: 8.00,
  },
};

// Export ABIs
export { SwapHubTokenABI, SwapHubDEXABI };

// Contract bytecodes would be generated by Hardhat/Foundry compilation
// For now, we'll use the deployed addresses approach
export const getContractConfig = (contractName: "token" | "dex") => {
  return {
    token: {
      abi: SwapHubTokenABI,
      name: "SwapHubToken",
    },
    dex: {
      abi: SwapHubDEXABI,
      name: "SwapHubDEX",
    },
  }[contractName];
};

// Helper to check if contracts are deployed
export const areContractsDeployed = (): boolean => {
  return (
    DEPLOYED_CONTRACTS.dex !== "" &&
    Object.values(DEPLOYED_CONTRACTS.tokens).some((addr) => addr !== "")
  );
};

// Helper to get token address
export const getTokenAddress = (symbol: string): string | null => {
  return DEPLOYED_CONTRACTS.tokens[symbol] || null;
};

// Helper to format address for display
export const formatAddress = (address: string): string => {
  if (!address) return "";
  return `${address.slice(0, 6)}...${address.slice(-4)}`;
};

// Storage keys for persisting deployed addresses
export const STORAGE_KEYS = {
  DEPLOYED_DEX: "swaphub_dex_address",
  DEPLOYED_TOKENS: "swaphub_token_addresses",
  NETWORK: "swaphub_network",
};

// Load deployed addresses from localStorage
export const loadDeployedAddresses = (): DeployedContracts | null => {
  if (typeof window === "undefined") return null;
  
  try {
    const dex = localStorage.getItem(STORAGE_KEYS.DEPLOYED_DEX);
    const tokens = localStorage.getItem(STORAGE_KEYS.DEPLOYED_TOKENS);
    
    if (dex && tokens) {
      return {
        dex,
        tokens: JSON.parse(tokens),
      };
    }
  } catch (e) {
    console.error("Error loading deployed addresses:", e);
  }
  
  return null;
};

// Save deployed addresses to localStorage
export const saveDeployedAddresses = (contracts: DeployedContracts): void => {
  if (typeof window === "undefined") return;
  
  localStorage.setItem(STORAGE_KEYS.DEPLOYED_DEX, contracts.dex);
  localStorage.setItem(STORAGE_KEYS.DEPLOYED_TOKENS, JSON.stringify(contracts.tokens));
};
